<?php
$translations = [
    'Manage Admins' => 'Manage Admins',
    'Add New Admin' => 'Add New Admin',
    'Name' => 'Name',
    'Email' => 'Email',
    'Phone' => 'Phone',
    'Date Added' => 'Date Added',
    'Actions' => 'Actions',
    'Delete' => 'Delete',
    'Are you sure you want to delete this admin?' => 'Are you sure you want to delete this admin?',
    'No other admins found' => 'No other admins found',
    'Manage Patients' => 'Manage Patients',
    'Patients List' => 'Patients List',
    'Back to Dashboard' => 'Back to Dashboard',
    'Gender' => 'Gender',
    'Blood Type' => 'Blood Type',
    'Age' => 'Age',
    'Join Date' => 'Join Date',
    'Male' => 'Male',
    'Female' => 'Female',
    'Not Selected' => 'Not Selected',
    'Years' => 'Years',
    'None' => 'None',
    'View' => 'View',
    'Are you sure you want to delete?' => 'Are you sure you want to delete?',
    'No patients found' => 'No patients found',
    'Manage Doctors' => 'Manage Doctors',
    'Add New Doctor' => 'Add New Doctor',
    'License' => 'License',
    'Fee' => 'Fee',
    'Suspend' => 'Suspend',
    'Manage Sections' => 'Manage Sections',
    'Add and edit clinical sections' => 'Add and edit clinical sections',
    'Add New Section' => 'Add New Section',
    'Edit' => 'Edit',
    'No sections found' => 'No sections found',
    'No medical sections added yet' => 'No medical sections added yet',
    'Add First Section' => 'Add First Section',
    'Subject' => 'Subject',
    'Date' => 'Date',
    'Image' => 'Image',
    'Title' => 'Title',
    'No posts published yet' => 'No posts published yet',
    'IQD' => 'IQD',
    'Are you sure you want to delete this doctor?' => 'Are you sure you want to delete this doctor?',

    // New keys for Create forms
    'Phone Number' => 'Phone Number',
    'Password' => 'Password',
    'Confirm Password' => 'Confirm Password',
    'Save Admin' => 'Save Admin',
    'Enter full name' => 'Enter full name',
    'Back to Admins' => 'Back to Admins',
    'User Information' => 'User Information',
    'Minimum 8 characters' => 'Minimum 8 characters',
    'Back to Doctors' => 'Back to Doctors',
    'Save Doctor' => 'Save Doctor',
    'Publish New Post' => 'Publish New Post',
    'Kurdish (Main)' => 'Kurdish (Main)',
    'Arabic' => 'Arabic',
    'English' => 'English',
    'Post Title (Kurdish)' => 'Post Title (Kurdish)',
    'Post Title (Arabic)' => 'Post Title (Arabic)',
    'Post Title (English)' => 'Post Title (English)',
    'Post Content (Kurdish)' => 'Post Content (Kurdish)',
    'Post Content (Arabic)' => 'Post Content (Arabic)',
    'Post Content (English)' => 'Post Content (English)',
    'Example for users' => 'Example for users',
    'Write info here' => 'Write info here',
    'Post Image' => 'Post Image',
    'Save Post' => 'Save Post',
    'Back to Dashboard' => 'Back to Dashboard',
    'Section Name (Kurdish)' => 'Section Name (Kurdish)',
    'Section Name (Arabic)' => 'Section Name (Arabic)',
    'Section Name (English)' => 'Section Name (English)',
    'Description (Kurdish)' => 'Description (Kurdish)',
    'Description (Arabic)' => 'Description (Arabic)',
    'Description (English)' => 'Description (English)',
    'Section Image' => 'Section Image',
    'Save Section' => 'Save Section',
    'Back to Sections' => 'Back to Sections',
    'Example: Eye Section' => 'Example: Eye Section',
    'Write note here' => 'Write note here',
   'Section Information' => 'Section Information',
   'Please fill info carefully' => 'Please fill info carefully'
];

$file = __DIR__ . "/resources/lang/en.json";
if (file_exists($file)) {
    $data = json_decode(file_get_contents($file), true) ?: [];
    foreach ($translations as $key => $val) {
        $data[$key] = $val;
    }
    file_put_contents($file, json_encode($data, JSON_UNESCAPED_UNICODE | JSON_PRETTY_PRINT));
}
echo "en.json updated.";
